Feature/sptd 26
tinkin-tech/you-owe-me pull request #10
Opened 2021-10-12 16:22 UTC by Edwin7319

Porcentaje de cobertura

2021-10-12 19:37 UTC, NicolasWebDev requested changes
Algunas observaciones @Edwin7319 . Bastante bien y un pull request bastante limpio.

2021-10-12 19:37 UTC, NicolasWebDev commented on tests/e2e/test_debt_report.py
> +        datetime.strptime("2021-10-01", "%Y-%m-%d"),
No es una pena @Edwin7319 hacer bajar la seguridad que nos puede dar nuestra prueba, con una sola muestra? Como te decía, en una prueba siempre hay que intentar tener dos casos, sino puede ser que un bug se nos esté escapando.

2021-10-12 19:37 UTC, NicolasWebDev commented on tests/e2e/test_code_duplicate_percentage.py
> +from src.__main__ import get_percentage_code_duplication
El nombre anterior quedaba mejor en inglés. `get_code_duplication_percentage` quiere decir `get el porcentaje de duplicación de código). Ahora para que sea inglés correcto faltaría el `of`.

2021-10-12 19:37 UTC, NicolasWebDev commented on src/utils/string.py
> +def convert_string_to_list_by_separator(text, separator):
Aquí estás básicamente creando un alias a la función `split` que es de la stdlib de python. Para qué? Cualquier persona que sabe de python sabe qué hace split, o sino lo puede buscar.

2021-10-12 19:37 UTC, NicolasWebDev commented on src/__main__.py
> +REGEX_TO_MATCH_DEEPEST_VALUE_INSIDE_JSON = "(?<=\\{)\\s*[^{]*?(?=[\\}])"
Ya vino el momento de poner como prefijo la herramienta correspondiente, no? Por ej. en este caso, indicar que es para leer el reporte del jest.
Porque a la final cada regex es sumamente acoplada al reporte de una herramienta en particular, y está bien.

2021-10-12 19:37 UTC, NicolasWebDev commented on src/__main__.py
> +    subprocess.run(
[ExtractMethod](https://refactoring.guru/extract-method), ya que lo estamos haciendo dos veces, o todavía no?

2021-10-12 19:37 UTC, NicolasWebDev commented on src/__main__.py
> +        total_lines_row, ","
En estos casos, por fines de documentación puede ser interesante indicar qué parámetro estamos seteando, para no tener que ver la definición de la función para entender qué está pasando.
```suggestion
        total_lines_row, separator=","
```

Pero lo dejo a tu criterio.

2021-10-12 19:37 UTC, NicolasWebDev commented on src/__main__.py
> +                f"{debt['COVERAGE']}"
Para qué los f-strings aquí?

2021-10-12 19:37 UTC, NicolasWebDev commented on src/__main__.py
> +    # get total, covered, skipped, pct separated by "," from LINES REPORT
pct?

2021-10-12 19:37 UTC, NicolasWebDev commented on src/__main__.py
> +    )[3]
[Magic numbers](https://refactoring.guru/replace-magic-number-with-symbolic-constant).

2021-10-18 13:50 UTC, Edwin7319 commented on src/__main__.py
> +    # get total, covered, skipped, pct separated by "," from LINES REPORT
@NicolasWebDev lo coloque de esa manera, ya que en el reporte de jest el campo porcentaje lo abrevia como PCT

2021-10-18 14:15 UTC, Edwin7319 commented on src/__main__.py
> +                f"{debt['COVERAGE']}"
Los usoo porque necesito obtener los valores del diccionario "debt", entonces para que sea mas legible utiliza los f-string

2021-10-18 15:32 UTC, NicolasWebDev commented on src/__main__.py
> +                f"{debt['COVERAGE']}"
Si quisieras, podrías usar un join en lugar de los ";", por eso preguntaba. O concatenar usando +. Abajo está un ejemplo con menos duplicación, pero es más difícil de entender, así que tu solución está super bien.

```python
+ "\n".join(
    [
        ";".join(
            [
                debt.get(key)
                for key in [
                    "DATE",
                    "CODE_DUPLICATION",
                    "IMPLEMENTATION_LINES",
                    "TEST_LINES",
                    "TOTAL_LINES",
                    "COVERAGE",
                ]
            ]
        )
        for debt in debts
    ]
)
```

Y de hecho este array de strings se podría ir a una constante llamada HEADERS o REPORT_HEADERS o algo así.

Con eso llegaríamos a esta otra versión:
```python
+ "\n".join(
    [
        ";".join([debt.get(column) for column in [REPORT_COLUMNS]])
        for debt in debts
    ]
)
```

La ventaja de esta opción, es que si tenemos que agregar más métricas, entonces solo modificamos la constante REPORT_COLUMNS, ya no hace falta tocar esta función de aquí.

2021-10-18 15:35 UTC, NicolasWebDev approved these changes
Ya, ahora sí perfecto, las pruebas siguen pasando y todo está bellisimo. Te pusé una respuesta adicional, como posibilidad, pero como quedó está perfect!

Siempre jodo sobre algunas cosas especificas, que me parecen como base, pero si ya las tienes integradas entonces se hace mucho más rápido el code review y llegamos a un código super entendible y que será mucho más fácil de mantener en el futuro, aunque hoy no nos demos cuenta!

Pero bien @Edwin7319 , está super.

2021-10-19 14:50 UTC, chan32167 commented on src/__main__.py
> +                f"{debt['COVERAGE']}"
Falta corregir esto para el approve me parece?

2021-10-21 17:41 UTC, Edwin7319 commented on src/__main__.py
> +                f"{debt['COVERAGE']}"
@chan32167 @NicolasWebDev ya elimine los f-string, ahi quedo mas limpio pero creo que un poco dificil de leer esas lineas de impresion en pantalla

2021-10-21 18:05 UTC, alextinkin approved these changes

2021-10-22 14:20 UTC, NicolasWebDev commented on src/__main__.py
> +                f"{debt['COVERAGE']}"
Bueno la verdad @chan32167 no hacía falta corregir, porque ya había hecho un "approve", era más un comentario jajaja.
@Edwin7319 sí es más difícil leer, pero cuando tendremos pruebas unitarias, entender qué hace la función quedará clarísimo, así que si el cuerpo es un pelin criptico no es tan grave. Lo bueno es que hemos bajado acoplamiento.

2021-10-22 14:21 UTC, merged