Feature/sptd 19
tinkin-tech/you-owe-me pull request #2
Opened 2021-09-14 23:53 UTC by Edwin7319

2021-09-16 21:41 UTC, NicolasWebDev requested changes

2021-09-16 21:41 UTC, NicolasWebDev commented on README.md
> +export PATH=$PATH:$HOME/.poetry/bin
Este comando no sería más parte de la instalación de poetry en sí, que de la instalación de las dependencias del proyecto?
En cual caso no es responsabilidad del dev al momento de instalar, ver si tiene poetry bien instalado o no?

Eso dice la doc sobre la instalación:

> The installer installs the poetry tool to Poetry’s bin directory. On Unix it is located at $HOME/.poetry/bin and on Windows at %USERPROFILE%\.poetry\bin.
> This directory will be automatically added to your $PATH environment variable, by appending a statement to your $HOME/.profile configuration (or equivalent files). If you do not feel comfortable with this, please pass the --no-modify-path flag to the installer and manually add the Poetry’s bin directory to your path.

[source](https://python-poetry.org/docs/#windows-powershell-install-instructions)

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    path_analyze_folder = console_arguments[1]
Querías decir `folder_path_to_analyze`? Otro detalle, en la programación usamos más el concepto de `directory`, que es común, que el de `folder`, que es la palabra que usa Microsoft. Ver por ej. este [SO post](https://stackoverflow.com/questions/5078676/what-is-the-difference-between-a-directory-and-a-folder/52964221).

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    console_arguments = sys.argv
No sé si la variable temporal trae taaaaanto. Podríamos decir que va documentando, pero sys.argv en python sí es super básico.

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    with open(json_reporter_path) as json_file:
El uso del `with` hace que el `close` no sea necesario.
> It is good practice to use the with keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point.

[source](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files)

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    complete_jscpd_command = 'jscpd {} --ignore "**/*.json,**/*.yml,**/node_modules/**" --reporters json --output ' \
Será útil guardar el reporte?

2021-09-16 21:41 UTC, NicolasWebDev commented on report/jscpd-report.json
> +{
AAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHh `.gitignore`

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +def read_reporter_json():
`read_json_report`?

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +def get_terminal_variables():
Serán realmente variables?

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    os.system('npm list -g jscpd || npm i -g jscpd@3.3.26')
Hace falta fijar esta versión en particular? No será de poner un mínimo quizás?

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    execute_jscpd(project_path)
Más que ejecutar jscpd, a nivel algo más abstracto, no estamos sacando la duplicación del código? Así si cambiamos de herramienta, no tenemos que cambiar todos los nombres? También un dev que no sepa qué es jscpd, no tiene que entenderlo para entender el código a nivel macro?

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    path_analyze_folder = console_arguments[1]
Ahorita si no se pasa un argumento al script, se muere con un mensaje un chance criptico.

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    read_reporter_json()
Aquí no esta línea no está haciendo nada, porque no haces nada con su valor de retorno.

2021-09-16 21:41 UTC, NicolasWebDev commented on src/__main__.py
> +    os.system('npm list -g jscpd || npm i -g jscpd@3.3.26')
No será de ejecutar los comandos de manera silenciosa? Porque ahorita saca un output que es bastante criptico para el usuario.

Lo que interesa por el momento, es tener como ouptut la duplicación, no sé si mucho más.

2021-09-16 21:45 UTC, NicolasWebDev requested changes
Ah y te olvidaste del criterio de aceptación que hemos agregado esta mañana
![Screenshot from 2021-09-16 16-44-06](https://user-images.githubusercontent.com/2276631/133689953-d8bf06bd-0c0e-4614-8b32-42c50c3b8984.png)

2021-09-17 13:34 UTC, NicolasWebDev requested changes
Te olvidaste de revisar algunos de los comentarios parece.

2021-09-17 13:34 UTC, NicolasWebDev commented on .gitignore
> +*.json
No es un poco radical ignorar TODOS los archivos json del repo? Porque seguramente después vamos a querer agregar un json, por ej. de configuración, y no vamos a entender bien por qué no aparece. En general en el .gitignore queremos ser bastante especificos en el path del archivo.

2021-09-17 13:34 UTC, NicolasWebDev commented on src/__main__.py
> +    print('No ha enviado el directorio a ser analizado')
Escribamos los mensajes al usuario en inglés mejor no? Porque si está en github y que queremos que otras personas lo terminen usando, mejor que sea en inglés de una vez.

2021-09-17 13:34 UTC, NicolasWebDev commented on src/__main__.py
> +    if sys.argv[1]:
Sigue fallando Edwin. Probarás antes de commitear vea.

![Screenshot from 2021-09-17 08-23-42](https://user-images.githubusercontent.com/2276631/133789725-d9daf653-b897-48c2-ab69-be6625607109.png)

2021-09-17 13:34 UTC, NicolasWebDev commented on src/__main__.py
> +    os.system('npm list -g jscpd || npm i -g jscpd@3.3.26')
Qué dices sobre estos dos comentarios a los cuales no respondiste @Edwin7319 ?

2021-09-17 13:34 UTC, NicolasWebDev commented on src/__main__.py
> +                             '--output  ./report/ '.format(directory_path)
Lo que te recomendaba @Edwin7319 , era más de manipular el reporte en una variable que ponerlo en un archivo. En general es considerado bastante mala práctica en las herramientas CLI manipular mucho el filesystem, menos aún en el Working Directory. En caso de que reeealmente necesites un archivo temporal, usa eso, un archivo temporal, que no conlleva riesgo de dañar archivos del usuario (ver https://docs.python.org/3/library/tempfile.html para crear archivos temporales).

Pero en este caso preciso, sí hubiera puesto en una variable personalmente, ahora todo el mundo tiene al menos 8Gb de RAM, así que mejor no darse las vueltas mucho.

También tenemos el problema que estás ahorita acoplando mucho tu código, porque si cambia el path del archivo, entonces tienes que modificar en varios lugares de tu código. Mejor ser más explicitos y pasar el reporte (entero o su path) de manera explicita al otro método que lo necesite.

2021-09-17 13:34 UTC, NicolasWebDev commented on src/__main__.py
> +    os.system('rm {}'.format(json_reporter_path))
Ves aquí está lo densazo, hacer un `rm` en un CLI.

2021-09-17 13:34 UTC, NicolasWebDev commented on src/__main__.py
>      return total_percentage
Seguimos sin hacer nada con este valor de retorno.

2021-09-17 13:44 UTC, Edwin7319 commented on src/__main__.py
>      return total_percentage
Si @NicolasWebDev 
, lo que pasa es que ese le estoy usando para escribir el CSV, pero esa función esta en el otro, porque pertenecía a la otra tarea

2021-09-17 13:51 UTC, Edwin7319 commented on src/__main__.py
> +    os.system('npm list -g jscpd || npm i -g jscpd@3.3.26')
@NicolasWebDev esa versión la coloque debido a que los flags cambiaban, ya que los que estan en la documentación oficial no son nada igual a los que se estan haciendo uso con la version 3.3.26 que es la última. Entonces para tratar de evitar errores coloque esa versión en particular

2021-09-17 13:52 UTC, Edwin7319 commented on src/__main__.py
> +    print('No ha enviado el directorio a ser analizado')
@NicolasWebDev, ya lo corrijo, pero ene se caso deberia estar el mensaje dentro de un raise Exception, no en simple print ??

2021-09-17 14:52 UTC, NicolasWebDev approved these changes

2021-09-17 15:26 UTC, Quezma approved these changes

2021-09-17 15:26 UTC, merged