Feature/sptd 23
tinkin-tech/you-owe-me pull request #3
Opened 2021-09-16 19:31 UTC by Edwin7319

2021-09-17 15:14 UTC, NicolasWebDev requested changes
Full detalles que ya hemos conversado no están implementados.

2021-09-17 15:14 UTC, NicolasWebDev commented on .gitignore
> +*.json
Mismo comentario que anteriormente.

2021-09-17 15:14 UTC, NicolasWebDev commented on .env
> +REGEX_ALL_FILES=**/*.{ts,tsx}
No typescript, y la idea es manejar 2 regexes: 1 para encontrar los archivos de implementación, y otra para encontrar los archivos de prueba, porque les vamos a reusar todo el tiempo. Y a la final tu REGEX_ALL_FILES sería la unión de los archivos que vienen de ambas regexes.

2021-09-17 15:14 UTC, NicolasWebDev commented on .env
> +MEASUREMENT_INTERVAL=7
No sería bueno indicar la unidad?

2021-09-17 15:14 UTC, NicolasWebDev commented on .gitignore
> +.idea
Te pongo aquí porque no sé dónde más ponerlo.
Para qué sirve el archivo `last-commit.txt`?

2021-09-17 15:14 UTC, NicolasWebDev commented on pyproject.toml
> +[tool.poetry.scripts]
Quizás sea bueno agregar en el README estas instrucciones? Entiendo que el `packages` de arriba y esta línea de aquí, es para correr lo? Cómo sería entonces?

2021-09-17 15:14 UTC, NicolasWebDev commented on report/report.csv
> +fecha;duplicacion
Para qué commitear este archivo?

2021-09-17 15:14 UTC, NicolasWebDev commented on src/constants/config.py
> +from dotenv import load_dotenv
Igual te lo anoto aquí.
Para qué commitear los *.pyc?

2021-09-17 15:14 UTC, NicolasWebDev commented on src/constants/config.py
> +MEASUREMENT_START_DATE = os.getenv("MEASUREMENT_START_DATE")
A qué nos sirven estas 4 declaraciones de constantes?

2021-09-17 15:14 UTC, NicolasWebDev commented on src/constants/config.py
> +    if MEASUREMENT_START_DATE is None or MEASUREMENT_END_DATE is None or MEASUREMENT_INTERVAL is None:
Y todo bien si `REGEX_ALL_FILES` está vacío entonces?

2021-09-17 15:14 UTC, NicolasWebDev commented on src/constants/config.py
> +    return {
Para qué cambiar los nombres que ya habías escogido? Ganamos algo con eso?

2021-09-17 15:14 UTC, NicolasWebDev commented on src/__main__.py
> +environment_variables = validate_environment_variables()
Más que validar las variables de entorno, no las cargamos?

2021-09-17 15:14 UTC, NicolasWebDev commented on src/__main__.py
> +
Por otro lado estas aquí declarando una variable global al archivo, lo que resulta en un acoplamiento mayor del código y hace que sea más difícil entender los inputs/outputs de los métodos.

2021-09-17 15:14 UTC, NicolasWebDev commented on src/__main__.py
> +    raise Exception('No ha enviado el directorio a ser analizado')
Inglés.

2021-09-17 15:14 UTC, NicolasWebDev commented on src/__main__.py
> +    end_date = datetime.strptime(environment_variables['end_date'], '%Y-%m-%d')
No sería chévere que nuestro `config.py`, además de cargar las variables, las tipee de una vez?

2021-09-17 15:14 UTC, NicolasWebDev commented on src/__main__.py
> +    while initial_date <= end_date:
Cómo reacciona tu programa si `end_date` es anterior a `start_date`?

2021-09-17 15:14 UTC, NicolasWebDev commented on .env
> +MEASUREMENT_START_DATE=2021-07-01
El .env por definición no se debería comitear, ya que tiene que depender del environment. Ahorita cómo está, no puedes de manera práctica setear otros valores en un servidor de producción por ej.
Si quieres documentar el uso del .env, a veces personas usan un .env.example.

2021-09-17 15:14 UTC, NicolasWebDev commented on pyproject.toml
> +python-dotenv = "^0.19.0"
Bueno de hecho no sé si soy yo o qué, pero no me funciona el `poetry install`.

![Screenshot from 2021-09-17 10-13-33](https://user-images.githubusercontent.com/2276631/133806811-1a18663d-7537-42b8-a3a7-223941f0d43d.png)

2021-09-17 15:14 UTC, NicolasWebDev commented on pyproject.toml
> +python-dotenv = "^0.19.0"
Así que no logro correr la cosa.

2021-09-17 15:50 UTC, kr3at commented on report/report.csv
> +date;duplication
Los archivos reports.csv, tambien se los va a subir ??? Aquí creo que esos a lo mejor deberían ir en el git ignore, porque no estoy seguro que si corremos de otro carpeta o proyecto eso se va a sobre escribir o se va a generar uno nuevo ???

2021-09-17 15:50 UTC, kr3at commented on src/__main__.py
> +        commits.append(commit_id)
Esta variable despues para que le usas????, porque realizas el append, pero no veo que despues se la este pasando a algun otro metodo o devolviendo la variable

2021-09-17 15:50 UTC, kr3at commented on src/constants/config.py
> +MEASUREMENT_START_DATE = os.getenv("MEASUREMENT_START_DATE")
No se si aquí tal vez se podría realizar el tipeo de las variables de entorno que comentas ???

2021-09-17 18:07 UTC, Edwin7319 commented on report/report.csv
> +fecha;duplicacion
@NicolasWebDev, listo ya lo ignoro

2021-09-17 18:09 UTC, Edwin7319 commented on src/constants/config.py
> +    return {
No ese fue error mio, pero ya coloque un solo nombre a las variables

2021-09-17 18:11 UTC, Edwin7319 commented on src/__main__.py
> +    while initial_date <= end_date:
@NicolasWebDev ya le agregue un error en ese caso, aunque antes lo que hacia era tomar unicamente la fecha de inicio y de ahi sacar el commit

2021-09-17 18:14 UTC, Edwin7319 commented on src/__main__.py
> +        commits.append(commit_id)
@kr3at la uso en el if, en cada bucle agrego el último commit de la fecha indicada y busco en el arreglo donde voy haciendo el append, en caso de que encuentre un commit repetido se detiene el analisis

2021-09-17 20:54 UTC, NicolasWebDev requested changes

2021-09-17 20:54 UTC, NicolasWebDev commented on .env.example
> +# date format : yyyy-mm-dd
Al correr el proyecto con las variables de .env.example en una rama que no es master, tengo estos errores.

![Screenshot from 2021-09-17 15-10-04](https://user-images.githubusercontent.com/2276631/133847742-2f5e7388-2980-4c80-8654-08d3942ac095.png)

2021-09-17 20:54 UTC, NicolasWebDev commented on .env.example
> +REGEX_IMPLEMENTATION_FILES=**/*.{js,jsx}
Para qué el gitkeep sobre la carpeta `report`?

2021-09-17 20:54 UTC, NicolasWebDev commented on README.md
> +**SCC**: To install SCC package, run the following command
Personalmente no tengo snap instalado y ha de ser el caso de mucha gente. No será más fácil poner un enlace al github de scc y que la persona se lo instale viendo las instrucciones allá?

2021-09-17 20:54 UTC, NicolasWebDev commented on README.md
> +$ sudo snap install sc
Otra pregunta: para qué instalar scc, si no lo estamos usando en el proyecto todavía?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +    raise Exception("The directory to be analyzed hasn't been sent")
```suggestion
    raise Exception("The directory to be analyzed hasn't been given")
```

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +        commits.append(commit_id)
Para que usar un arreglo cuando bastaría guardar solo el último commit?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +            print('Repeated commit')
Para qué este `print`?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
>      file_name = './report/report.csv'
Estos literales que vamos a potencialmente usar en diferentes lugares, es mejor que estén configurados de manera explicita como constante global al inicio del archivo, por buena práctica.

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +    header = ['date', 'duplication']
Lo mismo aquí.

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
>  def write_into_csv_report(data_to_write):
Una pregunta: por el momento, qué ganamos con guardar el csv en algún lado? Porque no sacarlo sobre stdout mejor? Y así nos evitamos todas las vueltas de abajo para manipular carpetas y archivos.

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +    measurement_start_date = environment_variables['MEASUREMENT_START_DATE']
Qué info adicional nos trae esta variable temporal?

Siempre que creas una variable temporal (o de hecho siempre que escribes lo que sea), pregúntate qué beneficios y qué costos puede traer.

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +    dates = get_measurement_dates_between_intervals()
Lo mismo aquí, para qué la variable temporal?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
>          commit_id = os.popen('cd {} && git rev-list --before {} -1 master'.format(directory_path, commit_date)).read()
Sería mejor no usar `master` (sabiendo además que en github la rama principal ya no se llama `master` pero `main`), sacando la rama actual.

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
>          commit_id = os.popen('cd {} && git rev-list --before {} -1 master'.format(directory_path, commit_date)).read()
Hace falta repetir el `cd` cada vez?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +    directory_path_to_analyze = get_directory_path_to_analyze()
Misma pregunta aquí: para qué la variable temporal?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +        os.system('cd {} && git checkout {} --quiet'.format(directory_path, commit_id.strip()))
Igual aquí para qué el `cd` repetido?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +def calculate_code_duplication(directory_path, commit_date):
Será la responsabilidad de `calculate_code_duplication` escribir en un archivo .csv?
No debería ser más bien solo sacar la duplicación de una carpeta y ya? Y qué otros se encarguen de manipular ese resultado?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/__main__.py
> +    os.system('npm list -g jscpd || npm i -g jscpd@3 --silent')
El `npm list` todavía no está silenciado.

2021-09-17 20:54 UTC, NicolasWebDev commented on src/constants/config.py
> +def load_environment_variables():
Ahorita como está, cada vez que vamos a querer agregar una variable, tenemos que:
1. crear una variable temporal, que saque el valor de la variable del env
2. acordarme que tengo que comprobar que tiene un valor seteado
3. acordarme que tengo que devolver su valor como parte de la respuesta

No fuera bacán, si quiero agregar una nueva variable que no necesite una validación compleja, solo poder agregarle en un array como constante, y el resto se hace automáticamente?

2021-09-17 20:54 UTC, NicolasWebDev commented on src/constants/config.py
> +        raise ValueError("Initial date must be less than end date")
```suggestion
        raise ValueError("The initial date must be before the end date")
```

2021-09-17 20:57 UTC, Quezma commented
> Full detalles que ya hemos conversado no están implementados. De hecho no tuve tiempo de acabar el review, porque ya tengo que salir a la vacuna, pero tampoco se me instala bien. A ti te funciona @Quezma ?

Lo voy a revisar en la noche, hoy no he tuve chance de revisar a detalle

2021-09-20 21:55 UTC, NicolasWebDev commented on .env.example
> +# date format : yyyy-mm-dd
Sigue con el error.

2021-09-20 21:55 UTC, NicolasWebDev commented on README.md
> +**SCC**: To install SCC package, run the following command
No está resuelto esto.

2021-09-20 21:55 UTC, NicolasWebDev commented on README.md
> +$ sudo snap install sc
No está resuelto esto.

2021-09-20 21:55 UTC, NicolasWebDev commented on .env
> +MEASUREMENT_INTERVAL=7
Esto sigue igual.

2021-09-21 14:45 UTC, NicolasWebDev requested changes

2021-09-21 14:45 UTC, NicolasWebDev commented on src/constants/config.py
> +def load_environment_variables():
Esto sigue.

2021-09-21 14:45 UTC, NicolasWebDev commented on src/__main__.py
> +
No será que deberíamos cargar las variables en la función `__main__` más bien? O por qué hacerlo afuera?

2021-09-21 14:56 UTC, NicolasWebDev requested changes
Ahorita el programa no me está funcionando para nada, creo que hay que pegar una chequeada en pair con el Marco para ir cerrando.

2021-09-21 14:56 UTC, NicolasWebDev commented on src/__main__.py
> +    commit_id_analyzed = ''
```suggestion
    previous_analyzed_commit = ''
```

2021-09-21 14:56 UTC, NicolasWebDev commented on src/__main__.py
> +        commit_id = subprocess.check_output(get_commit_id, shell=True).decode('utf-8')
```suggestion
        current_commit = subprocess.check_output(get_commit_id, shell=True).decode('utf-8')
```

2021-09-21 14:56 UTC, NicolasWebDev commented on src/__main__.py
> +        get_commit_id = 'cd {} && git rev-list -1 --before {} master ' \
Qué ganamos con esta variable temporal? Además el nombre me parece raro, porque es un verbo, cuando lo que representa realmente es un comando del shell.

2021-09-21 14:56 UTC, NicolasWebDev commented on src/__main__.py
> +def write_csv_report(data_to_write):
Esta función no se llama nunca.

2021-09-21 22:57 UTC, closed without merging