feature/refactorize
tinkin-tech/you-owe-me pull request #5
Opened 2021-09-21 22:58 UTC by Quezma

2021-09-21 23:24 UTC, NicolasWebDev requested changes
Cositas pequeñas y un bug.

2021-09-21 23:24 UTC, NicolasWebDev commented on pyproject.toml
> +black = "^21.9b0"
Está metido el black entonces? No hace falta configurar nada más? Ya está funcionando, solo con esta línea?

Como el PR se llama refactorize, no me esperaba su inclusión aquí!

2021-09-21 23:24 UTC, NicolasWebDev commented on src/__main__.py
>  def get_directory_path_to_analyze():
Será que aquí podemos usar un [Guard Clause](https://betterprogramming.pub/refactoring-guard-clauses-2ceeaa1a9da)? O no te gusta? Personalmente siempre me parece más legible.

2021-09-21 23:24 UTC, NicolasWebDev commented on src/__main__.py
> +        "npm list -g jscpd || npm i -g jscpd@3.3.26",
Mejor sería fijar jspcd a la 3.3, para tener más flexibilidad, no?

2021-09-21 23:24 UTC, NicolasWebDev commented on src/__main__.py
> +        % get_code_duplication_percentage(get_directory_path_to_analyze())
Arriba usas el `.format` y aquí usas el `%`. Decídete!

2021-09-21 23:24 UTC, NicolasWebDev commented on src/__main__.py
> +    code_duplication_report = subprocess.check_output(
![Screenshot from 2021-09-21 18-21-23](https://user-images.githubusercontent.com/2276631/134260265-f4ddc61e-013b-472c-8d5e-f68123eabfae.png)
![Screenshot from 2021-09-21 18-22-08](https://user-images.githubusercontent.com/2276631/134260355-d4fcdb1a-530c-46e2-b4b2-0ecb85f36a59.png)
![Screenshot from 2021-09-21 18-22-56](https://user-images.githubusercontent.com/2276631/134260363-7ff2b753-f0a2-4dd7-8240-2b73d988f038.png)

Estamos en bash, tendrán cuidado.

2021-09-22 17:09 UTC, Quezma commented on pyproject.toml
> +black = "^21.9b0"
Si, se puede agregar configuraciones al archivo `pyproject.toml`, pero las configuraciones iniciales son suficientes según black, incluso los archivos que queremos excluir los toma del `.gitignore` y si queremos agregar otros en el futuro lo tenemos que hacer en el `pyproject.toml`

2021-09-22 19:56 UTC, Quezma commented on src/__main__.py
>  def get_directory_path_to_analyze():
Si me parece bien, pero como no era una condición anidada no le veía mucho problema, pero ya lo agregué .

2021-09-22 20:03 UTC, Quezma commented on src/__main__.py
> +        "npm list -g jscpd || npm i -g jscpd@3.3.26",
le cambié a latest

2021-09-22 20:07 UTC, Quezma commented on src/__main__.py
> +    code_duplication_report = subprocess.check_output(
No puedo replicar el error

2021-09-22 20:47 UTC, kr3at approved these changes
ok

2021-09-22 22:27 UTC, NicolasWebDev requested changes
Un detalle y algo más importante, pero aparte de eso super bien.

2021-09-22 22:27 UTC, NicolasWebDev commented on src/__main__.py
> +    if not have_more_than_one_element(sys.argv):
```suggestion
    if not has_more_than_one_element(sys.argv):
```

2021-09-22 22:27 UTC, NicolasWebDev commented on src/__main__.py
> +def have_more_than_one_element(list):
```suggestion
def has_more_than_one_element(list):
```

2021-09-22 22:27 UTC, NicolasWebDev commented on src/__main__.py
> +    return get_element_by_index(
Aquí con este método, si no existe el reporte, retornan 0% por defecto. No sería mejor indicar que no se logró generar el reporte, que tragarse el error de manera silenciosa?

2021-09-23 14:02 UTC, Quezma commented on src/__main__.py
> +            "There isn't JSCPD result for the submitted directory"
Yo le quitaría la palabra JSCPD del mensaje de error, le estamos atando a la herramienta que estamos utilizando ahora y para el usuario que esté usando la herramienta no le aporta en nada saber que estamos usando JSCPD, que opinan?

2021-09-23 14:37 UTC, NicolasWebDev approved these changes

2021-09-23 14:37 UTC, merged