feature/SPTD-32
tinkin-tech/you-owe-me pull request #7
Opened 2021-09-27 14:28 UTC by Quezma

2021-09-27 15:57 UTC, NicolasWebDev requested changes

2021-09-27 15:57 UTC, NicolasWebDev commented on .gitignore
> +.vim
Quizás sea mejor subir esta parte arriba y dejar el comentario que estaba aquí, ya que fue auto-generado con gitignore.io y es más fácil saber dónde se acaba lo que agregó.
Además arriba hay una sección que @Edwin7319 agregó llamada justamente `editors`.

2021-09-27 15:57 UTC, NicolasWebDev commented on .pylintrc
> +[MASTER]
Por qué haber escogido guardar la config en un `.pylintrc`? Qué les parece si ponemos más bien en el `pyproject.toml`, para que toda la configuración de nuestro tooling esté centralizada ahí?

Lo que me molesta además, es que es un archivo oculto, y que los diferentes miembros del equipo ya ni se van a dar cuenta que está ahí, a pesar de que sea un archivo de vital importancia.

2021-09-27 15:57 UTC, NicolasWebDev commented on .pylintrc
> +suggestion-mode=yes
Por otro lado, quizás sea chévere agregar un script para correr pylint sobre todos los archivos del proyecto. Por qué hay N maneras diferentes de correrlo.

2021-09-27 15:57 UTC, NicolasWebDev commented on .pylintrc
> +# C0115 (missing-class-docstring)
```bash
✘2 ~/work/tinkin/you-owe-me [feature/SPTD-32|✔]$ poetry run pylint tests/e2e/test_code_duplicate_percentage.py
************* Module test_code_duplicate_percentage
tests/e2e/test_code_duplicate_percentage.py:1:0: E0401: Unable to import 'src.__main__' (import-error)

--------------------------------------------------------------------
Your code has been rated at -6.67/10 (previous run: -6.67/10, +0.00)
```

Ahorita cómo está, y corriendolo así, me da un error de import en el archivo de prueba. A ti sí te funciona @Quezma ? Con qué comando?

2021-09-27 15:57 UTC, NicolasWebDev commented on pyproject.toml
> +pre-commit = "^2.15.0"
Meter el pre-commit aquí, no es mezclar los PRs?

2021-09-27 16:05 UTC, Quezma commented on .pylintrc
> +[MASTER]
Lo puse en el archivo `.pylintrc` para que esté con tanto el archivo `pyproject.toml`, si quieren lo puedo mover al `toml` mismo.

2021-09-27 19:32 UTC, Quezma commented on .pylintrc
> +# C0115 (missing-class-docstring)
Agregué el comando para correr el script, parece que para correr de la mejor manera hay que usar este script:

```bash
find . -type f -name "*.py" | xargs pylint
```

2021-09-27 19:34 UTC, Quezma commented on pyproject.toml
> +pre-commit = "^2.15.0"
No me di cuenta que estaba trabajando sobre la misma rama, pero ya hago un push borrando esos commits

2021-09-28 14:36 UTC, NicolasWebDev requested changes

2021-09-28 14:36 UTC, NicolasWebDev commented on pyproject.toml
> +start = 'poetry run python src/__main__.py'
`poetry run`? Aquí sí, pero arriba no?

2021-09-28 14:45 UTC, NicolasWebDev approved these changes

2021-09-28 14:45 UTC, Edwin7319 approved these changes

2021-09-28 14:46 UTC, merged