Feature/sptd 24
tinkin-tech/you-owe-me pull request #9
Opened 2021-09-29 22:57 UTC by Edwin7319

2021-10-05 11:47 UTC, Quezma commented on .env.example
> +PATTER_IMPLEMENTATION_FILES=**/*.{js,jsx}
PATTERN?

2021-10-05 11:47 UTC, Quezma commented on README.md
> +## Dependencies
Esto no sería en el apartado de `Install project dependencies`? porque a la final es una dependencia más del proyecto

2021-10-05 11:47 UTC, Quezma commented on src/__main__.py
> +    return total_lines_list[0] - total_lines_list[1]
Esto puede que lo entiendas ahora, pero luego va a ser complicado mantener ya que no se sabe que representa cada item y porque los estas restando, en estos casos si prefiero crear variables temporales para entender que está pasando y saber que significa cada valor

2021-10-05 11:47 UTC, Quezma commented on src/__main__.py
> +        f'{"--exclude-dir=test" if analyze_test_files else ""}',
Usas el argumento `analyze_test_files` que es un `boolean` para validar si se pasa como `true` que excluya el directorio `test` pero si no pasa un valor o el valor es falso lo incluye, más bien no se debería llamar `exclude_test_files`?

2021-10-05 11:47 UTC, Quezma commented on src/__main__.py
> +                    directory_path, file_extensions
Hay forma de hacer que directory_path y file_extensions sean globales? no le veo tan bueno que se pasen estos argumentos por todas las funciones que tenemos y estas llamen a otras funciones que también reciben como argumento estas variables

2021-10-05 11:47 UTC, Quezma commented on src/__main__.py
> +    print(format_debt_report(debt_report_by_range))
Será que es necesario tener esa variable temporal

2021-10-05 11:47 UTC, Quezma commented on src/constants/config.py
> +        "PATTER_IMPLEMENTATION_FILES": os.getenv("PATTER_IMPLEMENTATION_FILES"),
Estos dos no se validan también que deban existir?

2021-10-05 11:47 UTC, Quezma commented on src/utils/git.py
> +            f"&& git rev-list -1 --before '{date} 00:00' {branch_name}",
Porque le tienes que aumentar la hora?

2021-10-05 21:37 UTC, Edwin7319 commented on src/__main__.py
> +        f'{"--exclude-dir=test" if analyze_test_files else ""}',
Si @Quezma , estoy deacuerdo

2021-10-05 21:41 UTC, Edwin7319 commented on src/__main__.py
> +    print(format_debt_report(debt_report_by_range))
Pienso que si, ya que sin esa variable temporal quedaria una funcion, dentro de una función y a su vez estas dos dentro de otra función, algo asi: 

![image](https://user-images.githubusercontent.com/51345148/136106740-130e6426-66be-42d6-bfe8-416c2281ed11.png)

Entonces yo lo veo mas limpio y facil de entender con la variable temporal, 


![image](https://user-images.githubusercontent.com/51345148/136106680-ef31c730-4bb8-490b-a922-5feabf826dfe.png)

2021-10-05 22:02 UTC, Edwin7319 commented on .env.example
> +PATTER_IMPLEMENTATION_FILES=**/*.{js,jsx}
Le puse el nombre pattern porque es en todos los comandos utilizan el flag --pattern  para esta sintaxis "**/test/*.{js,jsx}", entonces no se si este correcto pattern, o deberia regex, u otro???

2021-10-05 22:05 UTC, Edwin7319 commented on src/utils/git.py
> +            f"&& git rev-list -1 --before '{date} 00:00' {branch_name}",
Estaba proebando algunas configuraciones, pero ya lo quite

2021-10-05 22:42 UTC, Edwin7319 commented on src/__main__.py
> +                    directory_path, file_extensions
Si hay una forma, pero toca inicializar las variables en el main, con todo ya esta hecho de esa forma

![image](https://user-images.githubusercontent.com/51345148/136112616-c76159b1-307f-41f5-8676-679d9d1efd6d.png)

2021-10-06 04:55 UTC, Quezma commented on .env.example
> +PATTER_IMPLEMENTATION_FILES=**/*.{js,jsx}
Si está correcto solo que está con el nombré de `PATTER` y no `PATTERN`, creo que debí explicar mejor a que me refería jaja

2021-10-06 13:42 UTC, Quezma commented on src/__main__.py
> +                    directory_path, file_extensions
No lo veo mal realmente, me parece mucho mejor tener esos warnings de pylint a pasar a todas las funciones esas 2 propiedades.
Igualmente tenemos que ya ir pensando en clases entonces creo que es una buena solución por el momento.

Tu que opinas @NicolasWebDev .

2021-10-06 15:03 UTC, Edwin7319 commented on .env.example
> +PATTER_IMPLEMENTATION_FILES=**/*.{js,jsx}
Perdón no me fije bien ja ja
Ya esta resuelto

2021-10-06 16:22 UTC, NicolasWebDev commented
Te contesto por aquí @Quezma , sobre el tema de usar variables globales, porque github no me deja contestar en la misma conversación.
Realmente yo soy de la otra opinión jajaja.

Prefiero evitar variables globales, y pasar argumentos a las funciones.

Este tema de pasar a variables globales, qué ganamos?
Diría que ganamos que se lee más chévere, porque la lista de parámetros de las funciones es más corta. Es decir que veo yo solo un tema estético. Pero fundalmente no cambiamos nada, el acoplamiento sigue igual, solo que ahora se volvió implicito en lugar de ser explicito.

Por otro lado, qué perdemos?
1. Documentación del código: si tengo un parámetro explicito a mi función, me queda mucho más claro como cliente de esas funciones qué tengo que pasarles para que funcione todo.
2. Estamos acoplando más el código: al hacer una variable global, ya potencialmente todas nuestras funciones pueden acceder a su valor. Para poder saber si una función realmente está tocando (en lectura o en escritura) esa variable, me toca leer el cuerpo entero de la función, en lugar de solo leer la firma de la función. Igual nos va a causar problemas al momento de querer probar estas funciones, ya que toca setear más contexto. También qué pasa si una función modifica una variable global sin que nos demos cuenta?
Podría resumir un poco ese asunto a reemplazar una lista de 10 parámetros de una función, por un json con 10 key/values. Es estético no más, el acoplamiento de hecho es mayor (porque el formato de ese json tiene que ser preciso), y estamos obfuscando las cosas.

Por estas razones, estoy empezando a preferir siempre lo explicito sobre lo implícito, documentar mejor y desacoplar más las cosas. Pero si tenemos funciones con 40 parámetros, eso es otro asunto que se arregla con otros tipos de refactorizaciones. Típicamente y como lo dices @Quezma , sí vamos a necesitar empezar a pensar POO en lugar de scripting en siguientes commits.

Ahí haz como te dice tu corazón señor @Edwin7319 .

2021-10-06 16:41 UTC, NicolasWebDev requested changes
Par de comentarios sobre code smells, pero super bien en general.
Ya estamos conversando de temas más interesantes.

2021-10-06 16:41 UTC, NicolasWebDev commented on .env.example
> +EXTENSIONS_FILES=js,jsx
Es necesario esta variable? No podemos lograr lo mismo con las dos regexes de arriba? Porque estamos repitiendo un poco de info.

2021-10-06 16:41 UTC, NicolasWebDev commented on README.md
> +To install the SCC tool, follow the steps described [here](https://github.com/boyter/scc), which is the official documentation
```suggestion
To install the SCC tool, follow the steps described [here](https://github.com/boyter/scc), which is the official documentation.
```

2021-10-06 16:41 UTC, NicolasWebDev commented on src/__main__.py
> +                **get_implementation_and_test_lines(),
Este `get_implementation_and_test_lines()`, me parece que ahorita está obfuscando un poco las cosas y podría ir aquí mismo, ahorita me da la impresión que está acoplando más las cosas. Si es responsabilidad de `get_debt_report_by_rang_date` de coger diferentes métricas y guardarlo en un dict, no debería dividir esa responsabilidad con otras funciones. O no sé.

2021-10-06 16:41 UTC, NicolasWebDev commented on src/__main__.py
> +def get_report_of_code_lines(exclude_test_files=False):
No es muy aconsejado de tener una función que cambia su comportamiento basado en un booleano.
Ver estos artículos:
- https://martinfowler.com/bliki/FlagArgument.html
- https://medium.com/@amlcurran/clean-code-the-curse-of-a-boolean-parameter-c237a830b7a3
- https://understandlegacycode.com/blog/what-is-wrong-with-boolean-parameters/
- etc

Seguramente el 1er artículo puede ser el mejor, siendo de Martin Fowler, el gúru de la refactorización.

2021-10-06 16:41 UTC, NicolasWebDev commented on src/__main__.py
> +    )[1:3]
Magic Numbers.

2021-10-06 16:41 UTC, NicolasWebDev commented on src/__main__.py
> +        )
```suggestion
def format_debt_report(debt_list):
    return (
        "Date;Code Duplication;Implementation Lines;Test Lines; Total Lines\n"
        + "\n".join(
            [
                f"{debt['DATE']};{debt['CODE_DUPLICATION']};"
                f"{debt['IMPLEMENTATION_LINES']};"
                f"{debt['TEST_LINES']};{debt['TOTAL_LINES']}"
                for debt in debt_list
            ]
        )
```

2021-10-06 22:42 UTC, Edwin7319 commented on .env.example
> +EXTENSIONS_FILES=js,jsx
@NicolasWebDev para usar en CSS si es necesario, ya que en los flag recibe una cadena de texto unicamente de las extensiones a analizar, porque sino por defecto analiza a todos los archivos

2021-10-07 14:05 UTC, Edwin7319 commented on src/__main__.py
> +                **get_implementation_and_test_lines(),
@NicolasWebDev lo realize de esta manera, pero no se si este tan bien porque se esta llamando tres veces la misma funcion:

![image](https://user-images.githubusercontent.com/51345148/136400870-8de33d91-3e87-4c41-9f79-67c9b8e0687a.png)


![image](https://user-images.githubusercontent.com/51345148/136400905-54646a7e-ffc5-42a3-84a6-5949189a5401.png)

2021-10-07 14:36 UTC, Edwin7319 commented on src/__main__.py
> +    )[1:3]
@NicolasWebDev , esto no entiendo a que se refiere

2021-10-11 15:04 UTC, NicolasWebDev requested changes
3 detalles por mi lado.

2021-10-11 15:04 UTC, NicolasWebDev commented on README.md
> +$ git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; git switch $branch'
Quizás sea bueno comentar el por qué de esto, porque así no más me queda un pelin críptico. Y aclarar si toca hacer eso cada vez que cambiamos de rama, antes o después del checkout, etc.

2021-10-11 15:04 UTC, NicolasWebDev commented on .env.example
> +START_DATE=YYYY-MM-DD
Sabiendo que es un archivo de ejemplo mismo, no será mejor poner como ejemplo datos reales? Porque por ej aquí, PATTERN_TEST_FILES como desarrollador, no tengo idea de en qué formato tiene que ir.

2021-10-11 15:04 UTC, NicolasWebDev commented on src/__main__.py
> +                for debt in debt_list
Aquí en general, en lugar de `for elt in elt_list`, usamos `for elt in elts`. Por ej. `for dog in dogs`, o `for cat in cats`. Realmente que sea una lista, o un set, o una tupla, o lo que sea, no importa tanto. Lo que importa, es que sea iterable.

2021-10-11 21:16 UTC, NicolasWebDev requested changes
Algo más que me acabo de dar cuenta Edwin.

2021-10-11 21:16 UTC, NicolasWebDev commented on .env.example
> +PATTERN_TEST_FILES=**/test/*.{js,jsx}
Un error en este string me hizo dar cuenta que las variables `PATTERN` no están siendo usadas, así que mejor borrarlas.

![Screenshot from 2021-10-11 16-15-03](https://user-images.githubusercontent.com/2276631/136856435-c2602d9f-9310-4336-a897-7c46049fe0ca.png)

2021-10-11 21:41 UTC, NicolasWebDev requested changes

2021-10-11 21:41 UTC, NicolasWebDev commented on .env.example
> -PATTERN_IMPLEMENTATION_FILES=**/*.{js,jsx}
![Screenshot from 2021-10-11 16-41-32](https://user-images.githubusercontent.com/2276631/136859006-95f82bf6-1975-40b4-ae1f-8fad934679fd.png)

2021-10-11 21:49 UTC, Edwin7319 commented on .env.example
> -PATTERN_IMPLEMENTATION_FILES=**/*.{js,jsx}
@NicolasWebDev ya lo corregi, perdon se me paso borrar del config

2021-10-11 22:09 UTC, NicolasWebDev approved these changes

2021-10-11 22:14 UTC, Quezma approved these changes

2021-10-11 22:14 UTC, merged